name: Release Library

on:
  push:
    branches: ['main']
    paths:
      - pasta-lib/package.json
      - pasta-lib/.changeset/**
      - .github/workflows/release_library.yml

jobs:
  release_library:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pasta-lib

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup node and yarn
      uses: actions/setup-node@v3
      with:
        node-version: 17
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Check rust validity
      run: cargo check

    - name: Build WASM package
      run: wasm-pack build --target web

    - name: Replace package json
      run: cp ./package.json pkg/package.json

    - name: Install npm dependencies
      working-directory: ./pasta-lib/pkg
      run: yarn install --immutable
    
    - name: Make release with changeset
      uses: changesets/action@v1
      with:
        publish: yarn ci:release
        commit: 'ci: release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      working-directory: ./pasta-lib/pkg
